// File generated by FlutterFire CLI.
// Ce fichier est temporaire et doit être remplacé par celui généré par flutterfire configure
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Configurations Firebase par défaut pour chaque plateforme
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // Remplacer ces configurations par celles de votre projet Firebase
    return const FirebaseOptions(
      apiKey: "YOUR_API_KEY",
      appId: "YOUR_APP_ID",
      messagingSenderId: "YOUR_MESSAGING_SENDER_ID",
      projectId: "ninja-clicker",
    );
  }
}
