// File generated by FlutterFire CLI.
// Ce fichier est temporaire et doit être remplacé par celui généré par flutterfire configure
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Configurations Firebase par défaut pour chaque plateforme
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // Remplacer ces configurations par celles de votre projet Firebase
    return const FirebaseOptions(
        apiKey: "AIzaSyA7HLxjgqRF3Z16IW4Y8Rd7Ccg5CmskvZE",
        authDomain: "ninjaclicker-9bad6.firebaseapp.com",
        projectId: "ninjaclicker-9bad6",
        storageBucket: "ninjaclicker-9bad6.firebasestorage.app",
        messagingSenderId: "822565646211",
        appId: "1:822565646211:web:3d474169b312791b8150b6",
        measurementId: "G-7F6SJMK555");
  }
}
